/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.leftPanels;

import controller.TableSingleton;
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import view.centerPanels.NewTableCentralPanel;
import static view.leftPanels.NewTablePnlLeft.numOfAttributes;
import static view.leftPanels.NewTablePnlLeft.numOfInstances;
import view.main.MainGUI;

/**
 *
 * @author Vlada
 */
public class AtributeNamesPnlLeft extends javax.swing.JPanel {

    /**
     * Creates new form AtributeNamesLeftPanel
     */
    public AtributeNamesPnlLeft() {
        initComponents();

        this.add(new JLabel("Insert attribute names:"));
        for (int i = 0; i < NewTablePnlLeft.numOfAttributes; i++) {
            TextField txtField = new TextField(18);
            TableSingleton.getInstance().getTextFields().add(txtField);

            this.add(TableSingleton.getInstance().getTextFields().get(i));

        }
        JButton ok = new JButton("Ok");

        this.add(ok);

        ok.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {

                for (int i = 0; i < NewTablePnlLeft.numOfAttributes; i++) {
                    if (TableSingleton.getInstance().getTextFields().get(i).getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "You must enter all attribute names!");
                        return;
                    }

                }

                ConfirmTablepnlLeft panelLeft = new ConfirmTablepnlLeft();
                panelLeft.setSize(MainGUI.getInstance().getPnlLeft().getSize());
                MainGUI.getInstance().getPnlLeft().removeAll();
                MainGUI.getInstance().getPnlLeft().add(panelLeft);

                NewTableCentralPanel panelCenter = new NewTableCentralPanel();
                panelCenter.setSize(MainGUI.getInstance().getPnlCenter().getSize());
                MainGUI.getInstance().getPnlCenter().removeAll();
                MainGUI.getInstance().getPnlCenter().add(panelCenter);

                MainGUI.getInstance().validate();
                MainGUI.getInstance().repaint();

                panelLeft.setVisible(true);
                panelCenter.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
